#!/bin/bash

find . -name "*.rb"         >> cscope.files
find . -name "*.java"       >> cscope.files
find . -name "*.groovy"     >> cscope.files
find . -name "*.gsp"        >> cscope.files
find . -name "*.jsp"        >> cscope.files
find . -name "*.js"         >> cscope.files
find . -name "*.sh"         >> cscope.files
find . -name "*.properties" >> cscope.files

cscope -q -R -b -i cscope.files
ctags -L cscope.files
