#!/usr/bin/env bash

grep --color -I -r --exclude 'Gem*' --exclude 'tags' --exclude 'tags.temp' --exclude '*.gemspec' --exclude-dir 'target' --exclude-dir '.git' --exclude 'cscope.*' --exclude "*.log" --exclude "log*" --exclude-dir '.idea' --exclude "*.min.css" --exclude "*.puml" --exclude "swagger.json" --exclude-dir 'archive' "$@" .
