#!/bin/bash

grep --color -I -r --exclude 'Gem*' --exclude 'tags' --exclude 'tags.temp' --exclude '*.gemspec' --exclude-dir '.git' --exclude 'cscope.*' --exclude "*.html" --exclude "*.js" --exclude "*.log" --exclude 'batchelor_rubocop.txt' "$@" .
